### ISSUE TITLE
Rhythm Tools/Customization

### ISSUE THREAD

**Issue by qrrbrbirbel** [flashflashrevolution/rCubed#157]
I've always wanted focal point to stare at when playing, and the current options are either too big or too flashy

Using a small dot of a pleasing color has worked well for me. 

Though my method works for now, I don't want to have to keep writing a dot on my computer screen with highlighter XD

If adding it doesn't make enough sense for FFR, I thought a nice work-around or cool feature anyway would be to upload custom images or data for anything in the playing field (ex. replace 123456789 with TCHALOGEN when the engine is counting accuracy). That way I can turn I can just turn all of the value's into a period and stick one where it's needed

![focal point](https://user-images.githubusercontent.com/67676739/86385395-3461e500-bc5e-11ea-9f2a-31d2a17e83dc.png)

**Comment by Xyr00** [comment]
![image](https://user-images.githubusercontent.com/2185274/86387043-99b6d580-bc60-11ea-8497-72b57fb271cd.png)

Something like the above could be the Menu UI. "Editor" could open up a pop-up options box that allowed you to set:
Color (similar to other color-setting menu options)
Alpha (so that you can specify how transparent the dot is to control brightness - slider like music volume?)
Shape (perhaps a pre-defined list of shapes?)
Size (slider like music volume? pre-defined sizes?)

Location of the dot could be set in the actual game editor where location of everything else is set (and would only display to move/set it if the option is enabled).

Option would be disabled by default until a user enables it.

**Comment by qrrbrbirbel** [comment]
^^^this is what my idea looks like from someone with more brain cells than me XD

**Comment by qrrbrbirbel** [comment]
Also had another thought:
The color could also be synced to the judgement system instead of having a custom color

ex. dot is green when you hit a good, red when you miss one, brown for a boo, etc

**Comment by G-flat** [comment]
@all-contributors please add @qrrbrbirbel for ideas

**Comment by Psycast** [comment]
This can likely be closed with the PR #329 due to the inclusion of custom backgrounds during gameplay that can recreate the functionally requested and also expand it far beyond just a simple dot.
