### ISSUE TITLE
Chart previews within the client

### ISSUE THREAD

**Issue by SalemKitkat** [flashflashrevolution/rCubed#170]
It would be cool if there was a way to preview a chart on the client, its possible to do as you could take the code from the multiplayer spectator section (as that would show the chart), but you would have to remove the functions that do realtime updates to score.

I believe this would be a good feature as you would be able to analyse the chart either before, during or after playing it, so you can see what would cause you issues in accuracy etc. This would enable players to understand where they need to improve so they perform better.

**Comment by G-flat** [comment]
@all-contributors please add @SalemKitkat for ideas

**Comment by Zageron** [comment]
This is possible, so 👍ing it

**Comment by webbhost** [comment]
Just a note that the only concern here from an infrastructure standpoint is that it could significantly increase bandwidth usage and to some extent, sequential reads on the filesystem depending on if you are pulling the chart or the chart+music (preferred?). In my eyes, we don't need to be concerned about that due to the resources available.

**Comment by Psycast** [comment]
@all-contributors please add @Psycast for doc, maintenance
