### ISSUE TITLE
FCs get overridden by non-FC pb's

### ISSUE THREAD

**Issue by mat100payette** [flashflashrevolution/rCubed#2]
**Is your feature based on a frustration?**
I'm always frustrated when I have FC'd a song but then that FC gets replaced when I beat my personal best with a non-FC score.

**If so, Describe the solution you'd like**
FCs scores are kept somewhere so that the flag remains.

**Comment by Zageron** [comment]
This has historically been a feature, due to the removal of FC importance. If any other players, devs, or staff have opinions please share.

**Comment by mat100payette** [comment]
@Zageron The fix cannot simply be to keep the FC flag alone. That would invite players to mash all songs to complete the FC bar. What likely needs to be done is a redo of the FC definition so that:

1. ll FC flags are associated with a saved FC score;
2. A FC represents an acceptable score with 0 miss.

The latter point could be achieved by making the FC definition look like:
"Pass the song with 0 misses and a boocount lower than x% of the total notecount", where x could be something like 10 or 20, depending on how strict you want it to be (it cannot be too small however because the closer it is to 0%, the more it converges to a definition of 0 misses + 0 boos, which is far too constraining). This proposed solution would bring two positives: meaningful FC completion bar + indenpendance between FC scores and top equiv scores for a player.

**Comment by SalemKitkat** [comment]
I dont really see a point in having this as a feature tbh, if anything, a better equiv changing an fc to a non fc encourages you to get the fc again with a better score, thus meaning you can improve as a player. This would make an fc actually worth it in the long run, but what you propose just doesnt seem to encourage this tbh

**Comment by TCHalogen** [comment]
I'm fine with separating full combos and recorded scores, but not fine with some arbitrary definition of what a full combo is. A full combo doesn't need a redefined structure: if the number of notes that a user hit is equal to the number of the notes in a song, then they have hit all notes possible and should be rewarded with a full combo, regardless of the score's perceived quality.

If a user goes through the song and mashes their way through a full combo, then they have indeed completed the song with 0 misses and therefore deserve the credit for that. If the user has obtained a full combo on the song, then their achieving a better score should not remove that full combo at all as it doesn't take away from the fact that they have in fact done it at least once. If users want to go double time and play everything just to get their FC bar filled, so be it. Their ranks will suffer accordingly and the time spent grinding will be much longer than those who are actually improving organically. 

Redoing the full combo definition creates confusion, as newer players will not understand why their score with 0 misses is being translated as anything other than a full combo, since they did in fact hit every note in the song.

**Comment by danielgirard** [comment]
(My Opinion as a Lv.62 FFR Player) I would really appreciate having the FC flag separated from the top score. Sometimes I'm doing really well in a song but miss a note. Then I need to grind that same song over and over to be able to FC it. I feel like I would progress way more by doing other songs instead of grinding the same song over and over to get back my FC. To avoid that problem I normally miss 5 additional notes when I miss one note, to be able to beat my score with a FC.
